image: Visual Studio 2015

environment:
  nodejs_version: "6"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run standard
  - npm run test:node

build: off

branches:
  only:
    - master
