version: 2

jobs:
  build:
    environment:
      XCODE_SCHEME: test
      XCODE_WORKSPACE: test
      XCODE_PROJECT: test
      NODE_VERSION: '10.2.1'
    macos:
      xcode: 10.12.6
    steps:
    - checkout
    - run:
        name: Update submodules
        command: git submodule update --init
    - restore_cache:
        key: node-{{ .Environment.NODE_VERSION }}
    - restore_cache:
        key: emsdk-{{ checksum "script/install-emscripten.sh" }}
    - run:
        name: Install Node.js with nvm
        command: |
          export NVM_DIR=${HOME}/.nvm
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
          [ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"
          nvm install ${NODE_VERSION}
          nvm alias default ${NODE_VERSION}
          echo "[ -s \"${NVM_DIR}/nvm.sh\" ] && . \"${NVM_DIR}/nvm.sh\"" >> $BASH_ENV
    - run:
        name: Install node dependencies
        command: npm install
    - run:
        name: Build with emscripten
        command: script/install-emscripten.sh
    - save_cache:
        key: node-{{ .Environment.NODE_VERSION }}
        paths:
        - .nvm
    - save_cache:
        key: emsdk-{{ checksum "script/install-emscripten.sh" }}
        paths:
        - .emscripten_cache
        - emsdk-portable
    - run:
        name: Build emscripten
        command: npm run build:browser
    - run:
        name: Lint JavaScript
        command: npm run standard
    - run:
        name: Test Browser
        command: npm run test:browser
    - run:
        name: Test Node.js
        command: npm run test:node
    - run:
        name: Test native
        command: npm run test:native
