name: Build

on:
  push:

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: checkout
      run: git submodule update --init
        
    - name: Install node dependencies
      run: npm ci

    - name: Build with emscripten
      run: script/install-emscripten.sh

    - name: Build emscripten
      run: npm run build:browser

    - name: Lint JavaScript
      run: npm run standard

    - name: Test Browser
      run: npm run test:browser

    - name: Test Node.js
      run: npm run test:node

    - name: Test native
      run: npm run test:native

